name: profile_card
description: "Carte de profil Flutter - exercice widgets de base"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.3
  flutter_bloc: ^9.1.1
  equatable: ^2.1.0
  dio: ^5.11.0
  flutter_secure_storage: ^11.0.0
  bloc_concurrency: ^0.3.0
  stream_transform: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.5

flutter:
  uses-material-design: true