services:
  - type: web
    name: actualites-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: frankfurt
    healthCheckPath: /actuator/health
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGINES
        sync: false
